/**
 * interface-files — project-local agent interface shims.
 *
 * Thin, GENERATED pointers installed into a consuming repo so every agent
 * runtime (.codex / .claude / .agents) can trigger the workflow. The real law
 * lives in the engine's skills/; these shims carry an engineVersion marker so
 * `htw doctor` can detect stale shim text exactly like config drift (the 0.3.4
 * and 0.3.5 skill laws shipped to zero consumers whose shims predated them).
 *
 * Node ESM, built-ins only.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { commandSignaturesMarkdown } from "./command-specs.mjs";

const PACKAGE_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");

function engineVersion() {
  try {
    return JSON.parse(readFileSync(join(PACKAGE_ROOT, "package.json"), "utf8")).version || "0.0.0";
  } catch {
    return "0.0.0";
  }
}

const GENERATED = (v) =>
  `<!-- GENERATED by how-to-work@${v} — do not edit; refresh with \`npx --yes github:aneym/how-to-work interfaces --force\` -->`;

const HTW_SKILL = (v) => `---
name: htw
description: "/htw is the canonical How To Work entrypoint: docs, PRDs, scoping, grill questions, stage moves, ledger, docs serving. Say what you want after /htw (\\"write a doc on X\\", \\"scope Y\\", \\"grill me on Z\\", \\"send it\\") and it routes itself."
engineVersion: ${v}
---

${GENERATED(v)}

# /htw — the one entrypoint

This project uses the public \`aneym/how-to-work\` engine. Bootstrap, then route by intent — the author should never have to pick a sub-skill.

## Bootstrap (always, ~2 commands)

1. Read \`.agents/skill-config/workflow/config.json\` (ports, paths, gate mode, Tailscale).
2. Run \`npx --yes github:aneym/how-to-work doctor\` — it validates engine/config/docs health and prints exact fixes. Apply mechanical fixes with \`doctor --fix\` before doing anything else.
3. Read the full canonical skill for the protocol you routed to: \`npx --yes github:aneym/how-to-work skill how-to-work\` (or \`doc\`, \`grill\`, \`scope\`).

## Route by intent

| The author says…                        | Do                                                       |
| --------------------------------------- | -------------------------------------------------------- |
| "write a doc on…", "explainer", report  | doc protocol: \`htw new report <slug>\` → author → render |
| "scope…", "draft PRD", new feature idea | scope protocol: \`htw new prd <slug>\` → grill → PRD      |
| "grill me", open decisions              | grill protocol: cards in the doc + \`htw grill ask\`      |
| "send it", execute, build               | how-to-work send-it: stage set "In execution" first      |
| stage/progress/ledger updates           | \`htw stage set\` / \`htw ledger add\` — never hand-edit  |
| answers pasted in chat                  | \`htw grill resolve <slug>\` (reads stdin)                |
| "fix the docs", stale/broken docs       | \`/htw-doctor\`                                           |

${commandSignaturesMarkdown()}

## Hard rules

- Semantic source only (\`.doc.md\`); never hand-edit generated HTML.
- \`state.json\` is the stage authority; move stages with \`htw stage set\`.
- After posting grill questions, start the gate: \`htw grill ask --doc <slug> --apply\`.
- Serve before handoff; hand back the URL from \`htw link <path>\` (it verifies the listener).
`;

const HTW_DOCTOR_SKILL = (v) => `---
name: htw-doctor
description: "End-to-end docs-system repair for this repo. /htw-doctor diagnoses the How To Work setup (engine drift, stale renders, catalog gaps, stage divergence, hand-authored HTML, rotting questions), applies every mechanical fix, and grills the author on the judgment calls."
engineVersion: ${v}
---

${GENERATED(v)}

# /htw-doctor — fix the docs system end to end

Run the deterministic doctor first; it does everything mechanical. Your job is the remainder: the judgment calls it refuses to make.

## Protocol

1. \`npx --yes github:aneym/how-to-work doctor --json\` — read the full report.
2. \`npx --yes github:aneym/how-to-work doctor --fix\` — applies mechanical fixes: restamp config (\`init --migrate --force\`), refresh interface shims, re-render + re-register + re-index stale docs, sync divergent frontmatter stages from state.json, scaffold missing state/ledger files.
3. Re-run \`doctor --json\`. Anything left is a JUDGMENT item. Never silently decide these — grill the author (question cards in a maintenance doc, or direct questions in chat when the repo has no docs yet):
   - **Hand-authored PRD dirs** (index.html with no .doc.md): adopt (reverse-scaffold a source from the HTML + state.json), archive, or delete?
   - **Unmappable stage strings**: which canonical stage is each doc actually in?
   - **Open questions rotting** (unanswered grill cards): still relevant? Re-ask via \`htw grill ask --apply\`, or fold into decisions?
   - **Legacy how-we-work shims / configs**: remove?
4. Apply the author's answers with the atomic commands (\`htw stage set\`, \`htw grill resolve\`, \`htw ledger add\`), never hand-edits.
5. Closeout: \`doctor\` exits 0; report what changed, what was decided, and the served docs-index URL (\`htw link\`).
`;

const HTW_COMMAND = (v) => `---
description: "How To Work — one entrypoint for docs, PRDs, scoping, grill, stage moves, and docs serving; routes your intent itself"
allowed-tools: Bash, Read, Grep, Glob, Edit, Write
engineVersion: ${v}
---

${GENERATED(v)}

Use the project-local \`htw\` skill (.claude/skills/htw, .agents/skills/htw, or .codex/skills/htw). Bootstrap: read \`.agents/skill-config/workflow/config.json\`, run \`npx --yes github:aneym/how-to-work doctor\`, then route the intent below through the skill's intent table.

Intent:

$ARGUMENTS
`;

const HTW_DOCTOR_COMMAND = (v) => `---
description: "Diagnose and fix this repo's How To Work docs system end to end (drift, stale renders, catalog, stages), grilling the author on judgment calls"
allowed-tools: Bash, Read, Grep, Glob, Edit, Write
engineVersion: ${v}
---

${GENERATED(v)}

Follow the project-local \`htw-doctor\` skill: \`npx --yes github:aneym/how-to-work doctor --json\`, then \`doctor --fix\`, then grill the author on every remaining judgment item (hand-authored PRD dirs, unmappable stages, rotting questions) and apply answers with the atomic htw commands.

Focus / extra context:

$ARGUMENTS
`;

const LEGACY_SKILL = (v) => `---
name: how-to-work
description: Project-local How To Work docs, PRD, grill, and docs-server workflow. Canonical entrypoint is /htw; this long-form name is an alias.
engineVersion: ${v}
---

${GENERATED(v)}

# How To Work

\`/htw\` is the canonical entrypoint (see the \`htw\` skill next to this one) — route intent through it. This alias exists for compatibility; \`how-we-work\` is an even older legacy alias and must not be used for new prompts or docs.

Quick rules (full law: \`npx --yes github:aneym/how-to-work skill how-to-work\`):

- Read \`.agents/skill-config/workflow/config.json\` first; run \`npx --yes github:aneym/how-to-work doctor\` and apply \`--fix\`.
- Semantic source only; the engine renders/registers/indexes. Never hand-edit generated HTML.
- \`state.json\` is the stage authority — move stages with \`htw stage set <slug> <stage>\`.
- Ledger via \`htw ledger add\`; pasted answers via \`htw grill resolve\`; gate via \`htw grill ask --apply\`.
- Serve before handoff; send the \`htw link\` URL (Tailscale preferred), never a raw file path.

${commandSignaturesMarkdown()}
`;

const LEGACY_COMMAND = (v) => `---
description: Use the project-local How To Work docs, PRD, grill, and docs-server workflow (alias of /htw)
allowed-tools: Bash, Read, Grep, Edit, Write
engineVersion: ${v}
---

${GENERATED(v)}

Alias of \`/htw\` — use the local \`htw\` skill and its intent table.

Intent:

$ARGUMENTS
`;

function targets(v) {
  const runtimes = [".codex", ".claude", ".agents"];
  const out = [];
  for (const rt of runtimes) {
    out.push([join(rt, "skills", "htw", "SKILL.md"), HTW_SKILL(v)]);
    out.push([join(rt, "skills", "htw-doctor", "SKILL.md"), HTW_DOCTOR_SKILL(v)]);
    out.push([join(rt, "skills", "how-to-work", "SKILL.md"), LEGACY_SKILL(v)]);
    out.push([join(rt, "commands", "htw.md"), HTW_COMMAND(v)]);
    out.push([join(rt, "commands", "htw-doctor.md"), HTW_DOCTOR_COMMAND(v)]);
    out.push([join(rt, "commands", "how-to-work.md"), LEGACY_COMMAND(v)]);
    out.push([join(rt, "commands", "how-to.md"), LEGACY_COMMAND(v)]);
  }
  return out;
}

export function installAgentInterfaces(root, { force = false } = {}) {
  const v = engineVersion();
  const written = [];
  const skipped = [];
  for (const [rel, body] of targets(v)) {
    const abs = join(root, rel);
    const content = body.endsWith("\n") ? body : `${body}\n`;
    if (existsSync(abs) && !force) {
      // Same-version shims are current; only silently skip those. Anything
      // else is stale and needs --force (doctor reports it).
      skipped.push(rel);
      continue;
    }
    mkdirSync(dirname(abs), { recursive: true });
    writeFileSync(abs, content, "utf8");
    written.push(rel);
  }
  return { written, skipped };
}

/** Audit shims without writing: which are missing, which are stale (wrong version/content). */
export function auditAgentInterfaces(root) {
  const v = engineVersion();
  const missing = [];
  const stale = [];
  for (const [rel, body] of targets(v)) {
    const abs = join(root, rel);
    if (!existsSync(abs)) {
      missing.push(rel);
      continue;
    }
    const current = readFileSync(abs, "utf8");
    const expected = body.endsWith("\n") ? body : `${body}\n`;
    if (current !== expected) stale.push(rel);
  }
  return { missing, stale, engineVersion: v };
}
